### ISSUE TITLE
PCL Profile111 support

### ISSUE THREAD

**Issue by rodsjo** [ServiceStackApps/HelloMobile#3]
I would really like to see ServiceStack.Client and .Text support for PCL Profile111, with Windows Phone 8.1. While waiting, are there any workarounds for installing .Client and .Text in a Profile111 project?

**Comment by mythz** [comment]
We're never going to support WP in Client/Text libraries, it's too restrictive and now effectively a dead platform.

Since your ServiceModels only need a reference to ServiceStack.Interfaces with does support WP 8.1 (Profile 328) you should be able to use your DTOs with a HTTP Client that does support WP 8.1.
